// demo-frontend/src/app/features/home/home.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="home">
      <h1>Chào mừng đến với KenVerse</h1>
      <a routerLink="/login" class="login-btn">Đăng nhập</a>
    </div>
  `,
  styles: [`
    .home {
      background-color: #5865F2;
      height: 100vh;
      color: white;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      text-align: center;
    }
    h1 { font-size: 3rem; margin-bottom: 1.5rem; }
    .login-btn {
      padding: 0.75rem 1.5rem;
      font-size: 1rem;
      background-color: white;
      color: #5865F2;
      border: none;
      border-radius: 9999px;
      cursor: pointer;
      text-decoration: none;
    }
  `],
})
export class HomeComponent {}

<section class="landing">
  <div class="landing__bg"></div>
  <div class="landing__content">
    <div class="landing__logo">
      <img src="/logo.svg" alt="KenVerse" />
    </div>
    <h1>Chào mừng đến với KenVerse</h1>
    <p class="landing__tagline">Nơi bạn và bạn bè cùng trò chuyện, chơi game và kết nối.</p>
    <div class="landing__actions">
      <a routerLink="/login" class="landing__btn landing__btn--primary">Đăng nhập</a>
      <a routerLink="/register" class="landing__btn landing__btn--ghost">Tạo tài khoản</a>
    </div>
  </div>
  <div class="landing__decor landing__decor--1"></div>
  <div class="landing__decor landing__decor--2"></div>
</section>

// demo-frontend/src/Pages/Client/Home/index.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';

const Home: React.FC = () => {
    const navigate = useNavigate();

    return (
        <div
            style={{
                backgroundColor: '#5865F2', // Discord primary color
                height: '100vh',
                color: 'white',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                alignItems: 'center',
                textAlign: 'center',
            }}
        >
            <h1 style={{ fontSize: '3rem', marginBottom: '1.5rem' }}>
                Chào mừng đến với KenVerse
            </h1>
            <button
                style={{
                    padding: '0.75rem 1.5rem',
                    fontSize: '1rem',
                    backgroundColor: 'white',
                    color: '#5865F2',
                    border: 'none',
                    borderRadius: '9999px',
                    cursor: 'pointer',
                }}
                onClick={() => navigate('/login')}
            >
                Đăng nhập
            </button>
        </div>
    );
};

export default Home;
