// demo-frontend/src/app/layouts/user-footer-sidebar/user-footer-sidebar.component.ts
import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { AsyncPipe } from '@angular/common';
import { NzDropDownModule } from 'ng-zorro-antd/dropdown';
import { NzMenuModule } from 'ng-zorro-antd/menu';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { AuthService } from '../../core/services/auth.service';
import { AuthStateService } from '../../core/state/auth-state.service';

@Component({
  selector: 'app-user-footer-sidebar',
  standalone: true,
  imports: [AsyncPipe, NzDropDownModule, NzMenuModule, NzIconModule],
  template: `
    <div style="position: absolute; bottom: 10px; width: 390px; padding-left: 10px; z-index: 1000">
      <div style="position: sticky; bottom: 0; padding: 8px; background-color: #3b3b47; border-radius: 10px; display: flex">
        <div nz-dropdown [nzDropdownMenu]="menu" nzTrigger="click" nzPlacement="bottomLeft"
             style="display: flex; align-items: center; gap: 10px; width: 80%; padding: 6px 0; border-radius: 10px; cursor: pointer"
             (mouseenter)="hovered = true" (mouseleave)="hovered = false"
             [style.backgroundColor]="hovered ? '#41414b' : 'transparent'">
          <div style="position: relative; width: 36px; height: 36px">
            <img [src]="(authState.user$ | async)?.avatarUrl || '/logo.svg'" alt="avatar"
                 style="width: 100%; height: 100%; border-radius: 50%; object-fit: cover; background-color: #6b6967" />
            <span style="position: absolute; bottom: 0; right: 0; width: 10px; height: 10px; background-color: green; border-radius: 50%; border: 2px solid white"></span>
          </div>
          <div style="display: flex; flex-direction: column; align-items: flex-start">
            <span style="color: white; font-size: 16px">{{ (authState.user$ | async)?.displayName }}</span>
            <span style="color: white; font-size: 12px">Online</span>
          </div>
        </div>
      </div>
    </div>

    <nz-dropdown-menu #menu="nzDropdownMenu">
      <ul nz-menu class="menu-server-setting" style="background-color: #001529">
        <li nz-menu-item (click)="logout()">
          <div style="display: flex; justify-content: space-between; color: #f17875">
            <span>Log out</span>
            <span nz-icon nzType="logout"></span>
          </div>
        </li>
      </ul>
    </nz-dropdown-menu>
  `,
})
export class UserFooterSidebarComponent {
  readonly authState = inject(AuthStateService);
  private readonly authService = inject(AuthService);
  private readonly router = inject(Router);
  hovered = false;

  async logout(): Promise<void> {
    try {
      const refreshToken = localStorage.getItem('refreshToken') || '';
      await this.authService.logout(refreshToken);
      await this.router.navigate(['/login'], { replaceUrl: true });
    } catch (error) {
      console.error('Logout failed:', error);
    }
  }
}

// demo-frontend/src/layouts/UserFooterSideBar.tsx
import { Dropdown, Menu } from "antd"
import { useSelector } from "react-redux"
import { selectAuthUser } from "store/selectors/authSelectors"
import { ExportOutlined, LogoutOutlined } from '@ant-design/icons';
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useLogout } from "Connections/AppBackend/Auth";
import { refreshToken } from "features/auth/authAPI";


export default function UserFooterSideBar() {
    const user = useSelector(selectAuthUser)
    const [isHovered, setIsHovered] = useState(false);
    const navigate = useNavigate();
    const { mutateAsync } = useLogout();

    const serverMenu = (
        <Menu
            className="menu-server-setting"
            theme="dark"
            style={{
                backgroundColor: "#001529",
                width: "100%",
                placeSelf: "center"
            }}
            items={[
                {
                    key: 'leave',
                    label: (
                        <div style={{ display: "flex", justifyContent: "space-between" }}>
                            <span style={{ color: '#f17875' }}>Log out</span>
                            <LogoutOutlined style={{ color: '#f17875', fontSize: 14 }} />
                        </div>
                    ),
                    onClick: () => {
                        handleLogout()
                    },
                },
            ]}
        />
    );


    const handleLogout = async () => {
        try {
            const refreshToken = localStorage.getItem('refreshToken') || '';
            const response = await mutateAsync({ refreshToken });
            if (response) {
                navigate('/login', { replace: true });
            } else {
                console.error('Logout failed from server.');
            }
        } catch (error) {
            console.error('Logout failed:', error);
        }
    };

    return (
        <div style={{ position: "absolute", bottom: 10, width: 390, paddingLeft: 10, zIndex: 1000 }}>
            <div
                style={{
                    position: 'sticky',
                    bottom: 0,
                    padding: 8,
                    backgroundColor: '#3b3b47ff',
                    zIndex: 1,
                    borderRadius: 10,
                    display: 'flex',
                    flexDirection: 'row',
                }}
            >
                <Dropdown overlay={serverMenu} trigger={['click']} placement="bottomLeft">
                    <div
                        style={{ display: 'flex', alignItems: 'center', gap: 10, width: "80%", backgroundColor: isHovered ? '#41414bff' : 'transparent', paddingTop: 6, paddingBottom: 6, borderRadius: 10, cursor: 'pointer' }}
                        onMouseEnter={() => setIsHovered(true)}
                        onMouseLeave={() => setIsHovered(false)}
                    >
                        <div style={{ position: 'relative', width: 36, height: 36 }}>
                            <img
                                src={user?.avatarUrl || '/logo.png'}
                                alt={user?.username}
                                style={{
                                    width: '100%',
                                    height: '100%',
                                    borderRadius: '50%',
                                    objectFit: 'cover',
                                    display: 'block',
                                    backgroundColor: "#6b6967"
                                }}
                            />
                            <span
                                style={{
                                    position: 'absolute',
                                    bottom: 0,
                                    right: 0,
                                    width: 10,
                                    height: 10,
                                    backgroundColor: 'green',
                                    borderRadius: '50%',
                                    border: '2px solid white',
                                }}
                            />
                        </div>
                        <div style={{ display: 'flex', flexDirection: 'column', alignItems: "flex-start" }}>
                            <span style={{ color: 'white', fontSize: 16 }}>{user?.displayName}</span>
                            <span style={{ color: 'white', fontSize: 12 }}>Online</span>
                        </div>
                    </div>
                </Dropdown>
            </div>
        </div>
    )
}
