// demo-frontend/src/Pages/Client/App/Modal/CreateServer.tsx
import { Modal, Card, Space, Typography, Button, Form, Input, message, Upload, Image } from 'antd';
import { PlusCircleOutlined, LinkOutlined, ArrowLeftOutlined, CloseOutlined, LoadingOutlined, PlusOutlined } from '@ant-design/icons';
import { useState } from 'react';
import CustomInput from '../../../../Components/CustomInput';
import type { GetProp, UploadProps } from 'antd';
import { useCreateServer } from '../../../../Connections/AppBackend/Channel';
import { CreateServer } from '../../../../Connections/Types/Channel';
import { on } from 'events';

type FileType = Parameters<GetProp<UploadProps, 'beforeUpload'>>[0];
const { Title, Text } = Typography;
type Step = 'select' | 'create' | 'join';

export default function CreateServerModal({ open, onClose }: { open: boolean; onClose: () => void }) {
    const onCreatedSuccess = () => {
        form.resetFields();
        setImageUrl("");
        setLoadingImg(false);
        setStep('select');
        onClose();
    };
    const [step, setStep] = useState<Step>('select');
    const [loading, setLoading] = useState(false);
    const [form] = Form.useForm();
    const [loadingImg, setLoadingImg] = useState(false);
    const [imageUrl, setImageUrl] = useState<string>();
    const serverName = Form.useWatch('name', form);
    const inviteLink = Form.useWatch('invite', form);
    const isDisabled = step === 'create' ? !serverName : !inviteLink;
    const { mutate, isPending } = useCreateServer(onCreatedSuccess);
    const [messageApi, contextHolder] = message.useMessage();




    const onSubmit = async (values: any) => {
        if (step === 'create') {
            const input: CreateServer = {
                name: values.name,
                iconUrl: imageUrl,
                ownerId: localStorage.getItem("userID")?.toString(),
            }
            mutate(input, {
                onSuccess: () => {
                    messageApi
                        .open({
                            type: 'loading',
                            content: 'Server created!',
                            duration: 0.5,
                        });
                },
                onError: (err) => {
                    console.log(err);
                    messageApi
                        .open({
                            type: 'loading',
                            content: 'Action in progress..',
                            duration: 0.5,
                        })
                        .then(() => message.error(err.response?.data.message, 2.5));
                },
            });
        }
    }

    const renderContent = () => {
        if (step === 'select') {
            return (
                <Space direction="vertical" size="large" style={{ width: '100%' }}>
                    <Card
                        hoverable
                        onClick={() => setStep('create')}
                        style={{ textAlign: 'center', borderRadius: 12, backgroundColor: "#001529", borderColor: "#001529" }}
                    >
                        <Space direction="vertical">
                            <PlusCircleOutlined style={{ fontSize: 40, color: '#1677ff' }} />
                            <Title level={4} style={{ color: "#fff" }}>Create My Own</Title>
                            <Text type="secondary" style={{ color: "#fff" }}>Start a new server and invite friends</Text>
                        </Space>
                    </Card>
                    <Card
                        hoverable
                        onClick={() => setStep('join')}
                        style={{ textAlign: 'center', borderRadius: 12, backgroundColor: "#001529", borderColor: "#001529" }}
                    >
                        <Space direction="vertical">
                            <LinkOutlined style={{ fontSize: 40, color: '#52c41a' }} />
                            <Title level={4} style={{ color: "#fff" }}>Join a Server</Title>
                            <Text type="secondary" style={{ color: "#fff" }}>Enter an invite link to join existing</Text>
                        </Space>
                    </Card>
                </Space>
            );
        }

        const isCreate = step === 'create';
        return (
            <Form
                layout="vertical"
                form={form}
                style={{ marginTop: 12 }}
                onFinish={onSubmit}
            >
                {isCreate ? (
                    <div>
                        <Upload
                            name="IconUrl"
                            listType="picture-circle"
                            className="server-uploader"
                            showUploadList={false}
                            action={`${process.env.REACT_APP_URL_CHANNEL}/server/UploadIcon`}
                            headers={{
                                Authorization: `Bearer ${localStorage.getItem("token")}`,
                            }}
                            beforeUpload={beforeUpload}
                            onChange={handleChange}
                        >
                            {imageUrl ?
                                <Image
                                    src={imageUrl}
                                    width={100}
                                    height={100}
                                    style={{ borderRadius: '50%', objectFit: 'cover' }}
                                    preview={false}
                                />
                                : uploadButton}
                        </Upload>
                        <Form.Item
                            label="Server Name"
                            name="name"
                        >
                            <CustomInput style={{ backgroundColor: "#212126", color: "#fff", borderColor: "#212126" }} className='input-create-server' />
                        </Form.Item>
                    </div>

                ) : (
                    <Form.Item
                        label="Invite Link"
                        name="invite"
                    >
                        <CustomInput placeholder="https://kendz.site/xyz" style={{ backgroundColor: "#212126", color: "#fff", borderColor: "#212126" }} className='input-create-server' />
                    </Form.Item>
                )}
                <div style={{ display: "flex", justifyContent: "space-between" }}>
                    <Button
                        icon={<ArrowLeftOutlined />}
                        type="link"
                        onClick={() => {
                            form.resetFields();
                            setStep('select');
                        }}
                        style={{ paddingLeft: 0, color: "#fff" }}
                    >
                        Back
                    </Button>
                    <Button
                        htmlType="submit"
                        type="primary"
                        loading={isPending}
                        disabled={isDisabled}
                        block
                        style={{ width: 100, backgroundColor: "#5865f2" }}
                    >
                        {isCreate ? 'Create' : 'Join'}
                    </Button>
                </div>

            </Form>
        );
    };

    const getBase64 = (img: FileType, callback: (url: string) => void) => {
        const reader = new FileReader();
        reader.addEventListener('load', () => callback(reader.result as string));
        reader.readAsDataURL(img);
    };

    const beforeUpload = (file: FileType) => {
        const isJpgOrPng = file.type === 'image/jpeg' || file.type === 'image/png';
        if (!isJpgOrPng) {
            message.error('You can only upload JPG/PNG file!');
        }
        const isLt2M = file.size / 1024 / 1024 < 2;
        if (!isLt2M) {
            message.error('Image must smaller than 2MB!');
        }
        return isJpgOrPng && isLt2M;
    };

    const handleChange: UploadProps['onChange'] = (info) => {
        if (info.file.status === 'uploading') {
            setLoadingImg(true);
            return;
        }
        if (info.file.status === 'done') {
            // Get this url from response in real world.
            console.log(info)
            getBase64(info.file.originFileObj as FileType, (url) => {
                setLoadingImg(false);
                setImageUrl(info.file.response.data);
            });
        }
    };

    const uploadButton = (
        <button style={{ border: 0, background: 'none', cursor: "pointer" }} type="button">
            {loadingImg ? <LoadingOutlined style={{ color: "#fff" }} /> : <PlusOutlined style={{ color: "#fff" }} />}
            <div style={{ marginTop: 8, color: "#fff" }}>Upload</div>
        </button>
    );

    return (
        <Modal
            open={open}
            onCancel={() => {
                form.resetFields();
                setImageUrl("");
                setLoadingImg(false)
                setStep('select');
                onClose();
            }}
            footer={null}
            title={
                step == "select" ?
                    <div style={{ textAlign: "center" }}>
                        <p style={{ fontWeight: 'bold', fontSize: 22 }}>Create Your Server</p>
                        <p>Your server is where you and your friends hang out. Make yours and start talking</p>
                    </div>
                    : step == "create" ?
                        <div style={{ textAlign: "center" }}>
                            <p style={{ fontWeight: 'bold', fontSize: 22 }}>Customize Your Server</p>
                            <p>Give your new server a  personality with a name and an icon. You can always change it later.</p>
                        </div>
                        : <div style={{ textAlign: "center" }}>
                            <p style={{ fontWeight: 'bold', fontSize: 22 }}>Join a Server</p>
                            <p>Enter an invite below to join an existing server.</p>
                        </div>
            }
            centered
            width={400}
            destroyOnClose
            className="dark-modal"
            closeIcon={
                <CloseOutlined style={{ color: 'white', fontSize: 20 }} />  // ⬅️ tô màu & cỡ theo ý
            }
        >
            {contextHolder}
            {renderContent()}
        </Modal>
    );
}

// demo-frontend/src/app/features/app-shell/modals/create-server/create-server.component.ts
import { Component, EventEmitter, Input, Output, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzUploadModule } from 'ng-zorro-antd/upload';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzUploadFile } from 'ng-zorro-antd/upload';
import { environment } from '../../../../../environments/environment';
import { ChannelApiService } from '../../../../core/services/channel-api.service';
import { CustomInputComponent } from '../../../../shared/components/custom-input/custom-input.component';

type Step = 'select' | 'create' | 'join';

@Component({
  selector: 'app-create-server',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    NzModalModule,
    NzCardModule,
    NzButtonModule,
    NzFormModule,
    NzUploadModule,
    NzIconModule,
    CustomInputComponent,
  ],
  template: `
    <nz-modal
      [nzVisible]="open"
      [nzFooter]="null"
      [nzWidth]="400"
      nzCentered
      class="dark-modal"
      (nzOnCancel)="close()"
      [nzTitle]="title"
    >
      @if (step === 'select') {
        <div style="display: flex; flex-direction: column; gap: 16px">
          <nz-card nzHoverable (click)="step = 'create'" style="text-align: center; border-radius: 12px; background-color: #001529; border-color: #001529">
            <span nz-icon nzType="plus-circle" nzTheme="fill" style="font-size: 40px; color: #1677ff"></span>
            <h4 style="color: #fff">Create My Own</h4>
            <p style="color: #fff">Start a new server and invite friends</p>
          </nz-card>
          <nz-card nzHoverable (click)="step = 'join'" style="text-align: center; border-radius: 12px; background-color: #001529; border-color: #001529">
            <span nz-icon nzType="link" nzTheme="outline" style="font-size: 40px; color: #52c41a"></span>
            <h4 style="color: #fff">Join a Server</h4>
            <p style="color: #fff">Enter an invite link to join existing</p>
          </nz-card>
        </div>
      } @else {
        <form [formGroup]="form" (ngSubmit)="submit()" style="margin-top: 12px">
          @if (step === 'create') {
            <nz-upload
              nzName="IconUrl"
              nzListType="picture-card"
              class="server-uploader"
              [nzShowUploadList]="false"
              [nzAction]="uploadUrl"
              [nzHeaders]="uploadHeaders"
              (nzChange)="handleUpload($event)"
            >
              @if (imageUrl) {
                <img [src]="imageUrl" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover" />
              } @else {
                <div style="color: #fff">Upload</div>
              }
            </nz-upload>
            <nz-form-item nzLabel="Server Name">
              <app-custom-input formControlName="name" [customStyle]="inputStyle" inputClass="input-create-server" />
            </nz-form-item>
          } @else {
            <nz-form-item nzLabel="Invite Link">
              <app-custom-input formControlName="invite" placeholder="https://kendz.site/xyz" [customStyle]="inputStyle" />
            </nz-form-item>
            @if (errorMessage) {
              <p style="color: #dc3545">{{ errorMessage }}</p>
            }
          }
          <div style="display: flex; justify-content: space-between">
            <button nz-button nzType="link" type="button" style="color: #fff" (click)="back()">Back</button>
            <button nz-button nzType="primary" [nzLoading]="pending" [disabled]="isDisabled" type="submit" style="width: 100px; background-color: #5865f2">
              {{ step === 'create' ? 'Create' : 'Join' }}
            </button>
          </div>
        </form>
      }
    </nz-modal>
  `,
})
export class CreateServerComponent {
  @Input() open = false;
  @Input() ownerId?: string;
  @Output() closed = new EventEmitter<void>();

  private readonly fb = inject(FormBuilder);
  private readonly channelApi = inject(ChannelApiService);
  private readonly router = inject(Router);
  private readonly message = inject(NzMessageService);

  step: Step = 'select';
  pending = false;
  imageUrl = '';
  errorMessage = '';
  uploadUrl = `${environment.urlChannel}/server/UploadIcon`;
  uploadHeaders = { Authorization: `Bearer ${localStorage.getItem('token') || ''}` };
  inputStyle = { backgroundColor: '#212126', color: '#fff', borderColor: '#212126' };

  form = this.fb.group({ name: [''], invite: [''] });

  get title(): string {
    if (this.step === 'select') return 'Create Your Server';
    if (this.step === 'create') return 'Customize Your Server';
    return 'Join a Server';
  }

  get isDisabled(): boolean {
    return this.step === 'create' ? !this.form.value.name?.trim() : !this.form.value.invite?.trim();
  }

  handleUpload(info: { file: NzUploadFile }): void {
    if (info.file.status === 'done' && info.file.response?.data) {
      this.imageUrl = info.file.response.data;
    }
  }

  async submit(): Promise<void> {
    this.pending = true;
    this.errorMessage = '';
    try {
      if (this.step === 'create') {
        const server = await this.channelApi.createServerAndNavigate({
          name: this.form.value.name!,
          iconUrl: this.imageUrl || undefined,
          ownerId: this.ownerId,
        });
        this.message.success('Server created!');
        await this.router.navigate(['/server', server.id]);
      } else {
        const server = await this.channelApi.joinServerAndNavigate({
          Code: this.form.value.invite!,
          UserId: this.ownerId || '',
        });
        await this.router.navigate(['/server', server.id]);
      }
      this.close();
    } catch (err: unknown) {
      this.errorMessage = err instanceof Error ? err.message : 'Action failed';
    } finally {
      this.pending = false;
    }
  }

  back(): void {
    this.form.reset();
    this.errorMessage = '';
    this.step = 'select';
  }

  close(): void {
    this.form.reset();
    this.imageUrl = '';
    this.step = 'select';
    this.closed.emit();
  }
}
