// demo-frontend/src/app/features/auth/register/register.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzMessageService } from 'ng-zorro-antd/message';
import { AuthService } from '../../../core/services/auth.service';
import { CustomButtonComponent } from '../../../shared/components/custom-button/custom-button.component';
import { CustomInputComponent } from '../../../shared/components/custom-input/custom-input.component';
import { CustomPasswordInputComponent } from '../../../shared/components/custom-password-input/custom-password-input.component';
import { CustomSelectComponent } from '../../../shared/components/custom-select/custom-select.component';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    RouterLink,
    NzFormModule,
    CustomButtonComponent,
    CustomInputComponent,
    CustomPasswordInputComponent,
    CustomSelectComponent,
  ],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css',
})
export class RegisterComponent {
  private readonly fb = inject(FormBuilder);
  private readonly authService = inject(AuthService);
  private readonly router = inject(Router);
  private readonly message = inject(NzMessageService);

  loading = false;
  invalidDate = false;
  errors: Record<string, string> = {};

  years = Array.from({ length: new Date().getFullYear() - 1979 }, (_, i) => ({
    value: 1980 + i,
    label: 1980 + i,
  }));
  months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ].map((month, index) => ({ value: index + 1, label: month }));
  days = Array.from({ length: 31 }, (_, i) => ({ value: i + 1, label: i + 1 }));

  inputStyle = { backgroundColor: '#28282d', color: '#d0d1d3', borderColor: '#40444b' };
  selectStyle = { width: '30%', borderRadius: '8px' };

  form = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    displayName: ['', Validators.required],
    userName: ['', Validators.required],
    passwordHash: ['', Validators.required],
    day: [null as number | null, Validators.required],
    month: [null as number | null, Validators.required],
    year: [null as number | null, Validators.required],
  });

  validateDate(): void {
    const day = this.form.value.day;
    const month = this.form.value.month;
    const year = this.form.value.year;
    if (!day || !month || !year) {
      this.invalidDate = false;
      return;
    }
    const date = new Date(year, month - 1, day);
    this.invalidDate = !(
      date.getFullYear() === year &&
      date.getMonth() === month - 1 &&
      date.getDate() === day
    );
    if (this.invalidDate) {
      this.errors['dateOfBirth'] = 'Invalid date';
    } else {
      delete this.errors['dateOfBirth'];
    }
  }

  async submit(): Promise<void> {
    this.validateDate();
    if (this.form.invalid || this.invalidDate) {
      this.errors = { ...this.errors, form: 'Invalid' };
      return;
    }

    const { email, displayName, userName, passwordHash, day, month, year } = this.form.getRawValue();
    const dateOfBirth = day && month && year
      ? new Date(Date.UTC(year, month - 1, day)).toISOString().slice(0, 10)
      : undefined;

    this.loading = true;
    try {
      await this.authService.register({
        email: email!,
        displayName: displayName!,
        userName: userName!,
        passwordHash: passwordHash!,
        dateOfBirth,
      });
      this.message.success('Account created successfully!');
      await this.authService.login({ userName: userName!, password: passwordHash! });
      await this.router.navigate(['/server/@me'], { replaceUrl: true });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Registration failed';
      this.message.error(message);
    } finally {
      this.loading = false;
    }
  }
}

<div class="register-container">
  <div class="logo-container">
    <div class="logo"></div>
    <div style="color: white; font-size: 24px; font-weight: bold; margin-left: 10px">KenVerse</div>
  </div>

  <div class="register-box">
    <h3 style="color: white; text-align: center">Create account</h3>

    <form [formGroup]="form" (ngSubmit)="submit()">
      <nz-form-item>
        <nz-form-label><span style="font-size: 12px; font-weight: 600">EMAIL</span> <span style="color: rgb(245, 121, 118)">*</span></nz-form-label>
        <nz-form-control><app-custom-input formControlName="email" [customStyle]="inputStyle" /></nz-form-control>
      </nz-form-item>

      <nz-form-item>
        <nz-form-label><span style="font-size: 12px; font-weight: 600">DISPLAY NAME</span> <span style="color: rgb(245, 121, 118)">*</span></nz-form-label>
        <nz-form-control><app-custom-input formControlName="displayName" [customStyle]="inputStyle" /></nz-form-control>
      </nz-form-item>

      <nz-form-item>
        <nz-form-label><span style="font-size: 12px; font-weight: 600">USER NAME</span> <span style="color: rgb(245, 121, 118)">*</span></nz-form-label>
        <nz-form-control><app-custom-input formControlName="userName" [customStyle]="inputStyle" /></nz-form-control>
      </nz-form-item>

      <nz-form-item>
        <nz-form-label><span style="font-size: 12px; font-weight: 600">PASSWORD</span> <span style="color: rgb(245, 121, 118)">*</span></nz-form-label>
        <nz-form-control>
          <app-custom-password-input formControlName="passwordHash" [visibilityToggle]="false" [customStyle]="inputStyle" />
        </nz-form-control>
      </nz-form-item>

      <nz-form-item>
        <nz-form-label>
          <span style="font-size: 12px; font-weight: 600">DATE OF BIRTH</span>
          <span style="color: rgb(245, 121, 118)"> *</span>
        </nz-form-label>
        <div style="display: flex; justify-content: space-between; gap: 8px">
          <app-custom-select formControlName="day" placeholder="Day" [options]="days" [showSearch]="true" [customStyle]="selectStyle" (ngModelChange)="validateDate()" />
          <app-custom-select formControlName="month" placeholder="Month" [options]="months" [showSearch]="true" [customStyle]="selectStyle" (ngModelChange)="validateDate()" />
          <app-custom-select formControlName="year" placeholder="Year" [options]="years" [showSearch]="true" [customStyle]="selectStyle" (ngModelChange)="validateDate()" />
        </div>
      </nz-form-item>

      <app-custom-button type="primary" htmlType="submit" [loading]="loading" [buttonStyle]="{ width: '100%', backgroundColor: '#5865f2' }">
        Continue
      </app-custom-button>
    </form>

    <div style="text-align: left; margin-top: 16px">
      <a routerLink="/login" style="color: #5865f2">Already have an account?</a>
    </div>
  </div>
</div>

// demo-frontend/src/Pages/Client/Register/index.tsx
import React, { useEffect, useState } from 'react';
import { Form, Typography, message } from 'antd';
import './index.css';
import CustomInput from '../../../Components/CustomInput';
import CustomPasswordInput from '../../../Components/CustomPasswordInput';
import CustomSelect from '../../../Components/CustomSelect';
import CustomButton from '../../../Components/CustomButton';
import { useCreateUser } from '../../../Connections/AppBackend/User/Index';
import { useNavigate } from 'react-router-dom';
import { useLogin } from 'Connections/AppBackend/Auth';

const { Title, Text } = Typography;

interface FormValues {
  email: string;
  userName: string;
  displayName?: string;
  passwordHash: string;
  dateOfBirth: {
    day: number;
    month: number;
    year: number;
  }
}

interface ErrorState {
  [key: string]: string | undefined;
}

const RegisterForm: React.FC = () => {
  const navigate = useNavigate();
  const [messageApi, contextHolder] = message.useMessage();
  const [form] = Form.useForm<FormValues>();
  const [errors, setErrors] = useState<ErrorState>({});
  const [invalidDate, setInvalidDate] = useState<boolean>(false);
  const [day, setDay] = useState<number | undefined>();
  const [month, setMonth] = useState<number | undefined>();
  const [year, setYear] = useState<number | undefined>();
  const { mutate, isPending } = useCreateUser();
  const login = useLogin();

  const years = Array.from({ length: new Date().getFullYear() - 1979 }, (_, i) => 1980 + i);
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ].map((month, index) => ({ value: index + 1, label: month }));
  const days = Array.from({ length: 31 }, (_, i) => i + 1);

  const isValidDate = (y?: number, m?: number, d?: number): boolean => {
    if (!y || !m || !d) return true;

    const date = new Date(y, m - 1, d);
    return (
      date.getFullYear() === y &&
      date.getMonth() === m - 1 &&
      date.getDate() === d
    );
  };

  const handleChange = (value: number | undefined, type: 'day' | 'month' | 'year') => {
    const updatedDay = type === 'day' ? value : day;
    const updatedMonth = type === 'month' ? value : month;
    const updatedYear = type === 'year' ? value : year;

    if (type === 'day') setDay(value);
    if (type === 'month') setMonth(value);
    if (type === 'year') setYear(value);

    form.setFieldsValue({
      dateOfBirth: {
        day: updatedDay,
        month: updatedMonth,
        year: updatedYear,
      },
    });

    const valid = isValidDate(updatedYear, updatedMonth, updatedDay);
    setInvalidDate(!valid);

    if (!valid) {
      setErrors({ ...errors, dateOfBirth: 'Invalid date' });
      form.setFields([
        {
          name: 'dateOfBirth',
          errors: ['Ngày sinh không hợp lệ'],
        },
      ]);
    } else {
      setErrors({ ...errors, dateOfBirth: undefined });
      form.setFields([
        {
          name: 'dateOfBirth',
          errors: [],
        },
      ]);
    }
  };



  const onFinish = (values: FormValues) => {
    if (!invalidDate) {
      setErrors({});
      const dateOfBirth = values.dateOfBirth
        ? new Date(Date.UTC(values.dateOfBirth.year, values.dateOfBirth.month - 1, values.dateOfBirth.day))
        : undefined;
      const input = {
        email: values.email,
        userName: values.userName,
        displayName: values.displayName,
        passwordHash: values.passwordHash,
        dateOfBirth: dateOfBirth ? dateOfBirth.toISOString().slice(0, 10) : undefined,
      };
      mutate(input, {
        onSuccess: async () => {
          messageApi.open({ type: 'loading', content: 'Creating...', duration: 0.5 });
          messageApi.success('Account created successfully!', 2.5);

          try {
            await login.mutateAsync({
              userName: values.userName,
              password: values.passwordHash,
            });
            navigate('/server/@me', { replace: true });
          } catch (e) {
            message.error('Login failed. Please try again.');
          }
        },
        onError: (err) => {
          messageApi
            .open({
              type: 'loading',
              content: 'Action in progress..',
              duration: 0.5,
            })
            .then(() => message.error(err.response?.data.message, 2.5))
        },
      });
    }
  };

  const onFinishFailed = ({ errorFields }: { errorFields: any[] }) => {
    const newErrors: ErrorState = {};
    errorFields.forEach((field) => {
      newErrors[field.name[0]] = field.errors[0];
    });
    if (day === undefined || month === undefined || year === undefined) {
      newErrors.dateOfBirth = 'Ngày sinh không được để trống';
    }
    setErrors(newErrors);
  };


  useEffect(() => {
    if (login.isSuccess) {
      navigate('/server/@me');
    }
  }, [login.isSuccess, navigate]);

  return (
    <div className="register-container">
      {contextHolder}
      <div className='logo-container'>
        <div className="logo">
        </div>
        <div style={{ color: 'white', fontSize: 24, fontWeight: 'bold', marginLeft: 10 }}>
          KenVerse
        </div>
      </div>

      <div className="register-box">
        <Title level={3} style={{ color: 'white', textAlign: 'center' }}>
          Create account
        </Title>

        <Form
          form={form}
          name="register_demo_discord"
          layout="vertical"
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}
          autoComplete="off"
          requiredMark={false}
        >
          {/* Input giả để đánh lừa Chrome autofill */}
          <input type="text" name="fakeuser" autoComplete="username" style={{ display: 'none' }} />
          <input type="password" name="fakepassword" autoComplete="current-password" style={{ display: 'none' }} />

          <Form.Item
            label={
              <span>
                <span style={{ fontSize: 12, fontWeight: 600 }}>EMAIL</span>{' '}<span style={{ color: 'rgb(245, 121, 118)' }}>*</span>
                {errors.email != null && (
                  <span style={{ color: 'rgb(245, 121, 118)', fontStyle: "italic", fontSize: 12 }}> - Invalid</span>
                )}
              </span>
            } name="email"
            rules={[{ required: true, message: '' }, { type: 'email', message: '' }]}
          >
            <CustomInput
              size="large"
              style={{
                backgroundColor: "#28282d",
                color: '#d0d1d3',
                borderColor: '#40444b',
              }}
            />
          </Form.Item>

          <Form.Item
            label={
              <span>
                <span style={{ fontSize: 12, fontWeight: 600 }}>DISPLAY NAME</span>{' '}<span style={{ color: 'rgb(245, 121, 118)' }}>*</span>
                {errors.displayName != null && (
                  <span style={{ color: 'rgb(245, 121, 118)', fontStyle: "italic", fontSize: 12 }}> - Invalid</span>
                )}
              </span>
            }
            name="displayName"
            rules={[{ required: true, message: '' }]}
          >
            <CustomInput
              size="large"
              style={{
                backgroundColor: "#28282d",
                color: '#d0d1d3',
                borderColor: '#40444b',
              }}
            />
          </Form.Item>

          <Form.Item
            label={
              <span>
                <span style={{ fontSize: 12, fontWeight: 600 }}>USER NAME</span>{' '}<span style={{ color: 'rgb(245, 121, 118)' }}>*</span>
                {errors.userName != null && (
                  <span style={{ color: 'rgb(245, 121, 118)', fontStyle: "italic", fontSize: 12 }}> - Invalid</span>
                )}
              </span>
            } name="userName"
            rules={[{ required: true, message: '' }]}

          >
            <CustomInput
              size="large"
              style={{
                backgroundColor: "#28282d",
                color: '#d0d1d3',
                borderColor: '#40444b',
              }}
            />
          </Form.Item>

          <Form.Item
            label={
              <span>
                <span style={{ fontSize: 12, fontWeight: 600 }}>PASSWORD</span>{' '}<span style={{ color: 'rgb(245, 121, 118)' }}>*</span>
                {errors.passwordHash != null && (
                  <span style={{ color: 'rgb(245, 121, 118)', fontStyle: "italic", fontSize: 12 }}> Invalid</span>
                )}
              </span>
            }
            name="passwordHash"
            rules={[{ required: true, message: '' }]}
            help={null}
            style={{ textAlign: "left" }}
          >
            <CustomPasswordInput
              size="large"
              style={{
                backgroundColor: "#28282d",
                color: '#d0d1d3',
                borderColor: '#40444b',
              }}
              visibilityToggle={false}

            />
          </Form.Item>

          <Form.Item
            label={
              <span>
                <span style={{ fontSize: 12, fontWeight: 600, color: errors.dateOfBirth ? "#f57976" : "#b5bac1" }}>DATE OF BIRTH</span>{' '}
                <span style={{ color: 'rgb(245, 121, 118)' }}>*</span>
                {errors.dateOfBirth != null && (
                  <span style={{ color: 'rgb(245, 121, 118)', fontStyle: "italic", fontSize: 12 }}> - Invalid</span>
                )}
              </span>
            }
            validateStatus={invalidDate ? 'error' : undefined}
            name={'dateOfBirth'}
            required
          >
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <Form.Item name={'day'} noStyle rules={[{ required: true, message: '' }]} >
                <CustomSelect
                  className='register-select-dob'
                  dropdownClassName="register-select-dob-dropdown"
                  size="large"
                  options={days.map(day => ({ value: day, label: day }))}
                  placeholder="Day"
                  showArrow={true}
                  customStyle={{ width: "30%", border: errors.dateOfBirth ? "1px solid #f57976" : "none", borderRadius: 8 }}
                  dropdownStyle={{ backgroundColor: '#28282d' }}
                  showSearch
                  onChange={(value) => handleChange(value, 'day')}
                />
              </Form.Item>
              <Form.Item name={'month'} noStyle rules={[{ required: true, message: '' }]}>
                <CustomSelect
                  className='register-select-dob'
                  dropdownClassName="register-select-dob-dropdown"
                  size="large"
                  options={months}
                  placeholder="Month"
                  showArrow={true}
                  customStyle={{ width: "30%", border: errors.dateOfBirth ? "1px solid #f57976" : "none", borderRadius: 8 }}
                  dropdownStyle={{ backgroundColor: '#28282d' }}
                  showSearch
                  onChange={(value) => handleChange(value, 'month')}
                />
              </Form.Item>
              <Form.Item name={'year'} noStyle rules={[{ required: true, message: '' }]}>
                <CustomSelect
                  className='register-select-dob'
                  dropdownClassName="register-select-dob-dropdown"
                  size="large"
                  options={years.map(year => ({ value: year, label: year }))}
                  placeholder="Year"
                  showArrow={true}
                  customStyle={{ width: "30%", border: errors.dateOfBirth ? "1px solid #f57976" : "none", borderRadius: 8 }}
                  dropdownStyle={{ backgroundColor: '#28282d' }}
                  showSearch
                  onChange={(value) => handleChange(value, 'year')}
                />
              </Form.Item>
            </div>
          </Form.Item>


          <Form.Item>
            <CustomButton type="primary" htmlType="submit" block size="large" style={{ backgroundColor: '#5865f2' }} loading={isPending}>
              Continue
            </CustomButton>
          </Form.Item>
        </Form >

        <div style={{ textAlign: 'left', marginTop: 16 }}>
          <Text type="secondary" style={{ color: "#b5bac1" }}>
            <a href="/Login" style={{ color: "#5865f2" }}>Already have an account?</a>
          </Text>
        </div>
      </div >
    </div >
  );
};

export default RegisterForm;
