// demo-frontend/src/app/features/auth/login/login.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzTypographyModule } from 'ng-zorro-antd/typography';
import { AuthService } from '../../../core/services/auth.service';
import { AuthStateService } from '../../../core/state/auth-state.service';
import { CustomButtonComponent } from '../../../shared/components/custom-button/custom-button.component';
import { CustomInputComponent } from '../../../shared/components/custom-input/custom-input.component';
import { CustomPasswordInputComponent } from '../../../shared/components/custom-password-input/custom-password-input.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    RouterLink,
    NzFormModule,
    NzTypographyModule,
    CustomButtonComponent,
    CustomInputComponent,
    CustomPasswordInputComponent,
  ],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent {
  private readonly fb = inject(FormBuilder);
  private readonly authService = inject(AuthService);
  private readonly authState = inject(AuthStateService);
  private readonly router = inject(Router);

  loading = false;
  errors: Record<string, string> = {};

  form = this.fb.group({
    userName: ['', Validators.required],
    password: ['', Validators.required],
  });

  constructor() {
    if (this.authState.isAuthenticated) {
      this.router.navigate(['/server/@me'], { replaceUrl: true });
    }
  }

  async submit(): Promise<void> {
    this.errors = {};
    if (this.form.invalid) {
      this.errors = { userName: 'Required', password: 'Required' };
      return;
    }

    this.loading = true;
    try {
      await this.authService.login(this.form.getRawValue() as { userName: string; password: string });
      await this.router.navigate(['/server/@me'], { replaceUrl: true });
    } catch {
      this.errors = {
        userName: 'Invalid email or password',
        password: 'Invalid email or password',
      };
    } finally {
      this.loading = false;
    }
  }
}

<div class="login-container">
  <div class="logo-container">
    <div class="logo"></div>
    <div style="color: white; font-size: 24px; font-weight: bold; margin-left: 10px">KenVerse</div>
  </div>

  <div class="login-box">
    <h3 nz-typography style="color: white; text-align: center">Welcome back!</h3>

    <form [formGroup]="form" (ngSubmit)="submit()">
      <nz-form-item>
        <nz-form-label>
          <span style="font-size: 12px; font-weight: bold">EMAIL</span>
          <span style="color: rgb(245, 121, 118)"> *</span>
          @if (errors['userName']) {
            <span style="color: rgb(245, 121, 118); font-style: italic; font-size: 12px"> - {{ errors['userName'] }}</span>
          }
        </nz-form-label>
        <nz-form-control>
          <app-custom-input
            formControlName="userName"
            [customStyle]="{ backgroundColor: '#28282d', color: '#d0d1d3', borderColor: '#40444b' }"
          />
        </nz-form-control>
      </nz-form-item>

      <nz-form-item>
        <nz-form-label>
          <span style="font-size: 12px; font-weight: bold">PASSWORD</span>
          <span style="color: rgb(245, 121, 118)"> *</span>
          @if (errors['password']) {
            <span style="color: rgb(245, 121, 118); font-style: italic; font-size: 12px"> - {{ errors['password'] }}</span>
          }
        </nz-form-label>
        <nz-form-control>
          <app-custom-password-input
            formControlName="password"
            [visibilityToggle]="false"
            [customStyle]="{ backgroundColor: '#28282d', color: '#d0d1d3', borderColor: '#40444b' }"
          />
        </nz-form-control>
      </nz-form-item>

      <app-custom-button
        type="primary"
        htmlType="submit"
        [loading]="loading"
        [buttonStyle]="{ width: '100%', backgroundColor: '#5865f2' }"
      >
        Login
      </app-custom-button>
    </form>

    <div style="text-align: left; margin-top: 16px">
      <span style="color: #b5bac1">
        Need an account? <a routerLink="/register" style="color: #5865f2">Register</a>
      </span>
    </div>
  </div>
</div>

// demo-frontend/src/Pages/Client/Login/index.tsx
import React, { useEffect, useState } from 'react';
import { Button, Form, Input, message, Typography } from 'antd';
import './index.css';
import CustomInput from '../../../Components/CustomInput';
import CustomPasswordInput from '../../../Components/CustomPasswordInput';
import CustomButton from '../../../Components/CustomButton';
import { useLogin } from '../../../Connections/AppBackend/Auth';
import { useNavigate } from 'react-router-dom';


const { Title, Text } = Typography;

interface FormValues {
  userName: string;
  password: string;
}

interface ErrorState {
  [key: string]: string | undefined;
}

const LoginForm: React.FC = () => {
  const navigate = useNavigate();
  const [messageApi, contextHolder] = message.useMessage();
  const [form] = Form.useForm<FormValues>();
  const [errors, setErrors] = useState<ErrorState>({});
  const loginMutation = useLogin();

  const onFinish = async (values: FormValues) => {
    setErrors({});
    const input = {
      userName: values.userName,
      password: values.password,
    };
    try {
      await loginMutation.mutateAsync(input).then(res => {
        console.log(res)
      });
    }
    catch (error: any) {
      const newErrors: ErrorState = {
        userName: "Invalid email or password",
        password: "Invalid email or password",
      };
      setErrors(newErrors);
    }
  };

  const onFinishFailed = ({ errorFields }: { errorFields: any[] }) => {
    const newErrors: ErrorState = {};
    errorFields.forEach((field) => {
      newErrors[field.name[0]] = "Required";
    });
    setErrors(newErrors);
  };

  useEffect(() => {
    if (loginMutation.isSuccess) {
      navigate('/server/@me', { replace: true });
    }
  }, [loginMutation.isSuccess, navigate]);

  // useEffect(() => {
  //   if (isLoggedIn) {
  //     navigate('/app', { replace: true });
  //   }
  // }, [isLoggedIn, navigate]);

  return (
    <div className="login-container">
      {contextHolder}
      <div className='logo-container'>
        <div className="logo">
        </div>
        <div style={{ color: 'white', fontSize: 24, fontWeight: 'bold', marginLeft: 10 }}>
          KenVerse
        </div>
      </div>

      <div className="login-box">
        <Title level={3} style={{ color: 'white', textAlign: 'center' }}>
          Welcome back!
        </Title>

        <Form
          name="login_demo_discord"
          layout="vertical"
          onFinish={onFinish}
          onFinishFailed={onFinishFailed}
          autoComplete="off"
          requiredMark={false}
        >
          <input type="text" name="fakeuser" autoComplete="username" style={{ display: 'none' }} />
          <input type="password" name="fakepassword" autoComplete="current-password" style={{ display: 'none' }} />

          <Form.Item
            validateStatus={errors.userName ? 'error' : ''}
            label={
              <span>
                <span style={{ fontSize: 12, fontWeight: "bold" }}>EMAIL</span>{' '}<span style={{ color: 'rgb(245, 121, 118)' }}>*</span>
                {errors.userName != null && (
                  <span style={{ color: 'rgb(245, 121, 118)', fontStyle: "italic", fontSize: 12 }}> - {errors.userName}</span>
                )}
              </span>
            }
            name="userName"
            rules={[{ required: true, message: '' }]}
          >
            <CustomInput
              customStyle={{
                backgroundColor: "#28282d",
                color: '#d0d1d3',
                borderColor: '#40444b',
              }}
              size="large"
            />
          </Form.Item>

          <Form.Item
            validateStatus={errors.password ? 'error' : ''}
            label={
              <span>
                <span style={{ fontSize: 12, fontWeight: "bold" }}>PASSWORD</span>{' '}<span style={{ color: 'rgb(245, 121, 118)' }}>*</span>
                {errors.password != null && (
                  <span style={{ color: 'rgb(245, 121, 118)', fontStyle: "italic", fontSize: 12 }}> - {errors.password}</span>
                )}
              </span>
            }
            name="password"
            rules={[{ required: true, message: '' }]}
            help={null}
            style={{ textAlign: "left" }}
          >
            <CustomPasswordInput
              size="large"
              autoComplete="new-password"
              customStyle={{
                backgroundColor: "#28282d",
                color: '#d0d1d3',
                borderColor: '#40444b',
              }}
              visibilityToggle={false}
            />
          </Form.Item>

          <Form.Item>
            <CustomButton type="primary" htmlType="submit" block size="large" style={{ backgroundColor: '#5865f2' }} loading={loginMutation.isPending} >
              Login
            </CustomButton>
          </Form.Item>
        </Form>

        <div style={{ textAlign: 'left', marginTop: 16 }}>
          <Text type="secondary" style={{ color: "#b5bac1" }}>
            Need an account?<a href="/Register" style={{ color: "#5865f2" }}> Register</a>
          </Text>
        </div>
      </div>
    </div>
  );
};

export default LoginForm;
