// demo-frontend/src/Pages/Client/Server/ChannelSidebar/index.tsx
import { Dropdown, Menu } from 'antd';
import { PlusOutlined, MessageOutlined, AudioOutlined, DownOutlined, UsergroupAddOutlined, SettingOutlined, ExportOutlined, PlusCircleFilled, DeleteOutlined } from '@ant-design/icons';
import { Channel } from 'types';

interface ChannelMenuProps {
    channels: Channel[];
    onSelectChannel: (channelId: string) => void;
    onAddTextChannel: () => void;
    onAddVoiceChannel: () => void;
    serverName: string,
    setModalCreateChannelVisible: (visible: boolean) => void;
    isOwner: boolean,
    deleteServer: () => void;
    leaveServer: () => void;
}

export default function ChannelMenu({
    channels,
    onSelectChannel,
    onAddTextChannel,
    onAddVoiceChannel,
    serverName,
    setModalCreateChannelVisible,
    isOwner,
    deleteServer,
    leaveServer
}: ChannelMenuProps) {

    const serverMenu = (
        <Menu
            className="menu-server-setting"
            theme="dark"
            style={{
                backgroundColor: "#001529",
                width: "80%",
                placeSelf: "center"
            }}
            items={[
                {
                    key: 'createchannel',
                    label: (
                        <div style={{ display: "flex", justifyContent: "space-between" }}>
                            <span style={{ color: '#fff', fontSize: 14 }}>Create Channel</span>
                            <PlusCircleFilled style={{ color: '#fff', fontSize: 14 }} />
                        </div>
                    ),
                    onClick: () => setModalCreateChannelVisible(true),
                },
                {
                    key: 'invite',
                    label: (
                        <div style={{ display: "flex", justifyContent: "space-between" }}>
                            <span style={{ color: '#fff', fontSize: 14 }}>Invite People</span>
                            <UsergroupAddOutlined style={{ color: '#fff', fontSize: 14 }} />
                        </div>
                    ),
                    onClick: () => console.log('Invite')
                },
                {
                    key: 'settings',
                    label: (
                        <div style={{ display: "flex", justifyContent: "space-between" }}>
                            <span style={{ color: '#fff', fontSize: 14 }}>Server Settings</span>
                            <SettingOutlined style={{ color: '#fff', fontSize: 14 }} />
                        </div>
                    ),
                    onClick: () => console.log('Settings')
                },
                { type: 'divider' },
                ...(isOwner ? [{
                    key: 'delete',
                    label: (
                        <div style={{ display: "flex", justifyContent: "space-between" }}>
                            <span style={{ color: '#f17875', fontSize: 14 }}>Delete Server</span>
                            <DeleteOutlined style={{ color: '#f17875', fontSize: 14 }} />
                        </div>
                    ),
                    onClick: () => deleteServer(),
                }] : [{
                    key: 'leave',
                    label: (
                        <div style={{ display: "flex", justifyContent: "space-between" }}>
                            <span style={{ color: '#f17875' }}>Leave Server</span>
                            <ExportOutlined style={{ color: '#f17875', fontSize: 14 }} />
                        </div>
                    ),
                    onClick: () => leaveServer(),
                },]),
            ]}
        />
    );

    return (
        <Menu
            className="channel-menu"
            theme="dark"
            mode="inline"
            style={{ backgroundColor: '#2a2c35', color: 'white', border: 'none', borderTopLeftRadius: 20, borderBottomLeftRadius: 20 }}
        >
            <Dropdown overlay={serverMenu} trigger={['click']} placement="bottomLeft">
                <div
                    style={{
                        backgroundColor: "#2a2c35",
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        padding: 18,
                        borderBottom: '1px solid #555',
                        color: '#fff',
                        cursor: 'pointer',
                        userSelect: 'none',
                        borderTopLeftRadius: 20
                    }}
                >
                    <span style={{ fontWeight: 'bold' }}>{serverName}</span>
                    <DownOutlined />
                </div>
            </Dropdown>

            {/* TEXT CHANNELS */}
            <Menu.Item key="text-title" disabled style={sectionTitleStyle}>
                <div style={titleRowStyle}>
                    <span>Text Channels</span>
                    <PlusOutlined onClick={onAddTextChannel} style={plusStyle} />
                </div>
            </Menu.Item>
            {channels.filter((ch) => ch.type === 'Text').map((channel) => (
                <Menu.Item
                    key={channel.id}
                    onClick={() => onSelectChannel(channel.id)}
                    style={{ textAlign: "left" }}
                >
                    <div style={{ display: "flex", justifyContent: 'space-between' }}>
                        # {channel.name}
                        <MessageOutlined />
                    </div>
                </Menu.Item>
            ))}

            {/* VOICE CHANNELS */}
            <Menu.Item key="voice-title" disabled style={sectionTitleStyle}>
                <div style={titleRowStyle}>
                    <span>Voice Channels</span>
                    <PlusOutlined onClick={onAddVoiceChannel} style={plusStyle} />
                </div>
            </Menu.Item>
            {channels.filter((ch) => ch.type === 'Voice').map((channel) => (
                <Menu.Item
                    key={channel.id}
                    icon={<AudioOutlined />}
                    onClick={() => onSelectChannel(channel.id)}
                >
                    {channel.name}
                </Menu.Item>
            ))}
        </Menu>
    );
}


// Styles
const sectionTitleStyle = {
    cursor: 'default',
    color: '#888',
    paddingLeft: 16,
    paddingRight: 12,
    fontSize: 14,
    fontWeight: 'bold' as const,
    backgroundColor: '#2a2c35',
};

const titleRowStyle = {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
};

const plusStyle = {
    color: '#888',
    fontSize: 12,
    cursor: 'pointer',
};

// demo-frontend/src/app/features/server/channel-sidebar/channel-sidebar.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { NzMenuModule } from 'ng-zorro-antd/menu';
import { NzDropDownModule } from 'ng-zorro-antd/dropdown';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { Channel } from '../../../shared/types/channel';

@Component({
  selector: 'app-channel-sidebar',
  standalone: true,
  imports: [NzMenuModule, NzDropDownModule, NzIconModule],
  template: `
    <ul nz-menu nzTheme="dark" nzMode="inline" class="channel-menu sidebar">
      <li nz-submenu [nzTitle]="serverName" nz-dropdown [nzDropdownMenu]="menu">
        <ul nz-menu nzSelectable></ul>
      </li>

      <li nz-menu-item nzDisabled class="section-title">
        <div style="display: flex; justify-content: space-between">
          <span>Text Channels</span>
          <span nz-icon nzType="plus" (click)="addChannel.emit()" style="cursor: pointer"></span>
        </div>
      </li>
      @for (channel of textChannels; track channel.id) {
        <li nz-menu-item (click)="selectChannel.emit(channel.id)"># {{ channel.name }}</li>
      }

      <li nz-menu-item nzDisabled class="section-title">
        <div style="display: flex; justify-content: space-between">
          <span>Voice Channels</span>
          <span nz-icon nzType="plus" (click)="addChannel.emit()" style="cursor: pointer"></span>
        </div>
      </li>
      @for (channel of voiceChannels; track channel.id) {
        <li nz-menu-item><span nz-icon nzType="sound"></span> {{ channel.name }}</li>
      }
    </ul>

    <nz-dropdown-menu #menu="nzDropdownMenu">
      <ul nz-menu class="menu-server-setting">
        <li nz-menu-item (click)="addChannel.emit()">Create Channel</li>
        <li nz-menu-item (click)="invitePeople.emit()">Invite People</li>
        @if (isOwner) {
          <li nz-menu-item (click)="deleteServer.emit()"><span style="color: #f17875">Delete Server</span></li>
        } @else {
          <li nz-menu-item (click)="leaveServer.emit()"><span style="color: #f17875">Leave Server</span></li>
        }
      </ul>
    </nz-dropdown-menu>
  `,
  styles: [`
    .sidebar { background-color: #2a2c35; border-top-left-radius: 20px; border-bottom-left-radius: 20px; }
    .section-title { color: #888; font-weight: bold; }
  `],
})
export class ChannelSidebarComponent {
  @Input() channels: Channel[] = [];
  @Input() serverName = '';
  @Input() isOwner = false;
  @Output() selectChannel = new EventEmitter<string>();
  @Output() addChannel = new EventEmitter<void>();
  @Output() deleteServer = new EventEmitter<void>();
  @Output() leaveServer = new EventEmitter<void>();
  @Output() invitePeople = new EventEmitter<void>();

  get textChannels(): Channel[] {
    return this.channels.filter((c) => c.type === 'text');
  }

  get voiceChannels(): Channel[] {
    return this.channels.filter((c) => c.type === 'voice');
  }
}
