// demo-frontend/_react-backup/src/Pages/Client/Server/Modal/InvitePeople.tsx
import { Modal } from "antd";
import React from "react";
import { CloseOutlined, SearchOutlined, CopyOutlined } from '@ant-design/icons';
import { ServerDetail } from "types";
import CustomInput from "Components/CustomInput";
import CustomButton from "Components/CustomButton";

interface InvitePeopleModalProps {
    visible: boolean;
    onCancel: () => void;
    server: ServerDetail | null;
}

const InvitePeopleModal: React.FC<InvitePeopleModalProps> = ({ visible, onCancel, server }) => {

    const handleCopy = () => {
        if (server?.code) {
            navigator.clipboard.writeText(server.code);
        }
    };

    return (
        <Modal open={visible} className="dark-modal"
            closeIcon={
                <CloseOutlined style={{ color: 'white', fontSize: 20 }} />
            }
            footer={null}
            onCancel={() => {
                onCancel()
            }}
            title={<p style={{ fontWeight: 500, fontSize: 15, textAlign: "left", marginTop: 0 }}>Invite people to {server?.name}</p>}
        >
            <CustomInput placeholder="Seach for friends" className='input-create-server' style={{ backgroundColor: "#212126", color: "#fff", borderColor: "#212126" }} icon={<SearchOutlined />} iconPosition="right" />
            <p style={{ fontWeight: 500, fontSize: 15, textAlign: "left", marginTop: 16, marginBottom: 0 }}>Send a server invite link to a friend</p>
            <div style={{ backgroundColor: "#2f3136", padding: 10, borderRadius: 5, marginTop: 8, color: "#ebebebff", fontSize: 16, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                {server?.code}
                <CustomButton bgColor="#5865f2" hoverColor="#4957f1ff" style={{ border: "none" }} title="Copy" onClick={handleCopy}>
                    <CopyOutlined style={{ color: "#fff", fontSize: 16 }} />
                </CustomButton>
            </div>
        </Modal>
    )
}

export default InvitePeopleModal;

// demo-frontend/src/app/features/server/modals/invite-people/invite-people.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { ServerDetail } from '../../../../shared/types/server';
import { CustomInputComponent } from '../../../../shared/components/custom-input/custom-input.component';
import { CustomButtonComponent } from '../../../../shared/components/custom-button/custom-button.component';

@Component({
  selector: 'app-invite-people',
  standalone: true,
  imports: [NzModalModule, NzIconModule, CustomInputComponent, CustomButtonComponent],
  template: `
    <nz-modal
      [nzVisible]="visible"
      class="dark-modal"
      [nzFooter]="null"
      (nzOnCancel)="cancelled.emit()"
      [nzTitle]="'Invite people to ' + (server?.name || '')"
    >
      <app-custom-input placeholder="Search for friends" [customStyle]="inputStyle" />
      <p style="color: #fff; margin-top: 16px">Send a server invite link to a friend</p>
      <div class="code-box">
        {{ server?.code }}
        <app-custom-button [buttonStyle]="{ border: 'none', backgroundColor: '#5865f2' }" (click)="copy()">
          <span nz-icon nzType="copy"></span>
        </app-custom-button>
      </div>
    </nz-modal>
  `,
  styles: [`
    .code-box {
      background-color: #2f3136;
      padding: 10px;
      border-radius: 5px;
      margin-top: 8px;
      color: #ebebeb;
      font-size: 16px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
  `],
})
export class InvitePeopleComponent {
  @Input() visible = false;
  @Input() server: ServerDetail | null = null;
  @Output() cancelled = new EventEmitter<void>();

  inputStyle = { backgroundColor: '#212126', color: '#fff', borderColor: '#212126' };

  copy(): void {
    if (this.server?.code) {
      navigator.clipboard.writeText(this.server.code);
    }
  }
}
