// demo-frontend/src/Pages/Client/DirectMessage/AddFriendSideBar/index.tsx
import { Tabs, Tooltip } from 'antd';
import { useEffect, useState } from 'react';
import { m, motion } from 'framer-motion';
import { TeamOutlined, CloseOutlined, CheckOutlined, StopOutlined } from '@ant-design/icons';
import CustomInput from 'Components/CustomInput';
import CustomButton from 'Components/CustomButton';
import { useAddFriend, useCancelFriendRequest, useUpdateUserRelationship } from 'Connections/AppBackend/UserRelationship';
import { FriendPending } from 'types/user';
import { useSelector } from 'react-redux';
import { selectAuthUser } from 'store/selectors/authSelectors';
import { userRelationshipStatus } from 'shared';

const { TabPane } = Tabs;

export default function AddFriendSideBar({ friendPending }: { friendPending: FriendPending[] }) {
    const [activeTab, setActiveTab] = useState('add');
    const [addresseeName, setAddresseeName] = useState('');
    const [messageSubmit, setMessageSubmit] = useState('');
    const sentRequests = friendPending.filter(friend => friend.isSender);
    const receivedRequests = friendPending.filter(friend => !friend.isSender);
    const { id: ownerId } = useSelector(selectAuthUser) || {};
    const { mutate, isSuccess, isError } = useAddFriend();
    const { mutate: mutateUpdate, isSuccess: isSuccessUpdate, isError: isErrorUpdate } = useUpdateUserRelationship();
    const { mutate: mutateCancel, isSuccess: isSuccessCancel, isError: isErrorCancel } = useCancelFriendRequest();

    const onSubmit = () => {
        if (!addresseeName.trim()) return;
        const input = {
            requesterId: ownerId || '',
            addresseeName
        };
        mutate(input, {
            onSuccess: async () => {
                setMessageSubmit('Friend request sent successfully to ' + addresseeName);
            },
            onError: (err) => {
                setMessageSubmit(err.response?.data.message || 'Add friend failed');
            },
        });

    };

    useEffect(() => {
        setAddresseeName('');
    }, [activeTab])


    const handleAccept = (id: string) => {
        const data = {
            userID: ownerId || '',
            friendID: id,
            status: userRelationshipStatus.Accepted
        }
        mutateUpdate(data, {
            onError: (err) => {

            }
        })
    };

    const handleCancel = (id: string) => {
        const data = {
            userID: ownerId || '',
            friendID: id,
        }
        mutateCancel(data, {
            onError: (err) => {

            }
        });
    }

    return (
        <div style={{
            backgroundColor: 'rgb(48 48 49)',
            display: 'flex',
            flexDirection: 'column',
            height: '100%',
            borderTopRightRadius: 20,
            borderBottomRightRadius: 20
        }}>
            <div
                style={{
                    borderBottom: '1px solid #555',
                    height: 59,
                    alignItems: 'center',
                    paddingLeft: 16,
                    display: 'flex',
                }}
            >
                <div>
                    <TeamOutlined style={{ fontSize: 20, color: "#fff" }} />
                    <span style={{ marginLeft: 8, color: "#fff", fontSize: 16, fontWeight: 600 }}>
                        Friends
                    </span>
                </div>

                <Tabs
                    activeKey={activeTab}
                    onChange={setActiveTab}
                    tabBarStyle={{
                        marginBottom: 0,
                        borderBottom: 'none',
                        marginLeft: 32,
                    }}
                >
                    <TabPane
                        tab={
                            <div className={`custom-tab ${activeTab === 'pending' ? 'active' : ''}`}>
                                Pending
                            </div>
                        }
                        key="pending"
                    />
                    <TabPane
                        tab={
                            <div className={`custom-tab ${activeTab === 'add' ? 'active' : ''}`}>
                                Add Friend
                            </div>
                        }
                        key="add"
                    />
                </Tabs>
            </div>

            {/* Content */}
            <div style={{ padding: 16, color: '#fff', flex: 1 }}>
                {activeTab === 'add' && (
                    <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.3 }}
                    >
                        <div style={{ textAlign: "left", fontSize: 18, fontWeight: 500, marginBottom: 16 }}>
                            <h3 style={{ marginTop: 0, marginBottom: 0 }}>Add Friend</h3>
                            <h5 style={{ marginTop: 10, marginBottom: 0, fontWeight: 400 }}>You can add friends with their KenVerse username</h5>
                        </div>
                        <div style={{ position: 'relative', width: '100%' }}>
                            <CustomInput
                                placeholder='You can add friends with their KenVerse username'
                                size="large"
                                style={{
                                    backgroundColor: "#212126",
                                    color: "#fff",
                                    borderColor: isSuccess ? "#28a745" : isError ? "#dc3545" : "#212126",
                                    paddingRight: 120, // chừa khoảng cho button
                                    height: 50,

                                }}
                                className="input-create-server"
                                onPressEnter={onSubmit}
                                onChange={(e) => setAddresseeName(e.target.value)}
                            />
                            <CustomButton
                                style={{
                                    position: 'absolute',
                                    top: 4,
                                    right: 4,
                                    height: 'calc(100% - 8px)',
                                    backgroundColor: "#5865F2",
                                    color: "#fff",
                                    border: "none",
                                    padding: '0 16px',
                                }}
                                disabled={!addresseeName.trim()}
                                onClick={onSubmit}
                            >
                                Send Friend Request
                            </CustomButton>
                        </div>
                        <span style={{ color: isSuccess ? "#28a745" : isError ? "#dc3545" : "#212126", float: "left", marginTop: 8 }}>{messageSubmit}</span>

                    </motion.div>
                )}

                {activeTab === 'pending' && (
                    <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.3 }}
                    >
                        {friendPending.length === 0 ? (
                            <p style={{ color: '#aaa' }}>No pending friend requests.</p>
                        ) : (
                            <>
                                {receivedRequests.length > 0 && (
                                    <div style={{ marginBottom: 24 }}>
                                        <h4 style={{ color: '#fff', marginBottom: 12, textAlign: "left", paddingLeft: 10, fontWeight: 500 }}>Receive ({receivedRequests.length})</h4>
                                        {receivedRequests.map(friend => (
                                            <div
                                                key={friend.id}
                                                style={{
                                                    display: 'flex',
                                                    alignItems: 'center',
                                                    justifyContent: 'space-between',
                                                    backgroundColor: '#2c2c2f',
                                                    padding: '12px 16px',
                                                    borderRadius: 8,
                                                    marginBottom: 12
                                                }}
                                            >
                                                <div style={{ display: 'flex', alignItems: 'center' }}>
                                                    <img
                                                        src={friend.avatarUrl || '/logo.png'}
                                                        alt={friend.displayName}
                                                        style={{
                                                            width: 40,
                                                            height: 40,
                                                            borderRadius: '50%',
                                                            objectFit: 'cover',
                                                            marginRight: 12
                                                        }}
                                                    />
                                                    <div>
                                                        <div style={{ fontWeight: 600, color: '#fff' }}>{friend.displayName}</div>
                                                        <div style={{ fontSize: 13, color: '#aaa', textAlign: "left" }}>{friend.userName}</div>
                                                    </div>
                                                </div>
                                                <div>
                                                    <Tooltip title="Accept">
                                                        <CustomButton
                                                            style={{
                                                                width: 40,
                                                                height: 40,
                                                                color: "#fff",
                                                                border: "1px solid #393b47",
                                                                backgroundColor: "#393b47",
                                                                borderRadius: "100%",
                                                                marginRight: 12
                                                            }}
                                                            onClick={() => handleAccept(friend.id)}
                                                            hoverColor="#28a745"
                                                            bgColor="#393b47"
                                                        >
                                                            <CheckOutlined />
                                                        </CustomButton>
                                                    </Tooltip>
                                                    <Tooltip title="Reject">
                                                        <CustomButton
                                                            style={{
                                                                width: 40,
                                                                height: 40,
                                                                color: "#fff",
                                                                border: "1px solid #393b47",
                                                                backgroundColor: "#393b47",
                                                                borderRadius: "100%"
                                                            }}
                                                            onClick={() => handleCancel(friend.id)}
                                                            hoverColor="#dc3545"
                                                            bgColor="#393b47"
                                                        >
                                                            <StopOutlined />
                                                        </CustomButton>
                                                    </Tooltip>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                )}

                                {sentRequests.length > 0 && (
                                    <div>
                                        <h4 style={{ color: '#fff', marginBottom: 12, textAlign: "left", paddingLeft: 10, fontWeight: 500 }}>Sent ({sentRequests.length})</h4>
                                        {sentRequests.map(friend => (
                                            <div
                                                key={friend.id}
                                                style={{
                                                    display: 'flex',
                                                    alignItems: 'center',
                                                    justifyContent: 'space-between',
                                                    backgroundColor: '#2c2c2f',
                                                    padding: '12px 16px',
                                                    borderRadius: 8,
                                                    marginBottom: 12
                                                }}
                                            >
                                                <div style={{ display: 'flex', alignItems: 'center' }}>
                                                    <img
                                                        src={friend.avatarUrl || '/logo.png'}
                                                        alt={friend.displayName}
                                                        style={{
                                                            width: 40,
                                                            height: 40,
                                                            borderRadius: '50%',
                                                            objectFit: 'cover',
                                                            marginRight: 12
                                                        }}
                                                    />
                                                    <div>
                                                        <div style={{ fontWeight: 600, color: '#fff' }}>{friend.displayName}</div>
                                                        <div style={{ fontSize: 13, color: '#aaa', textAlign: "left" }}>{friend.userName}</div>
                                                    </div>
                                                </div>
                                                <Tooltip title="Cancel">
                                                    <CustomButton
                                                        style={{
                                                            width: 40,
                                                            height: 40,
                                                            color: "#fff",
                                                            border: "1px solid #393b47",
                                                            backgroundColor: "#393b47",
                                                            borderRadius: "100%"
                                                        }}
                                                        onClick={() => handleCancel(friend.id)}
                                                        hoverColor="rgb(70 72 87)"
                                                        bgColor="#393b47"
                                                    >
                                                        <CloseOutlined />
                                                    </CustomButton>
                                                </Tooltip>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </>
                        )}
                    </motion.div>
                )}
            </div>
        </div >
    );
}

// demo-frontend/src/app/features/direct-message/add-friend-sidebar/add-friend-sidebar.component.ts
import { Component, Input, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NzTabsModule } from 'ng-zorro-antd/tabs';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzToolTipModule } from 'ng-zorro-antd/tooltip';
import { AuthStateService } from '../../../core/state/auth-state.service';
import { UserRelationshipApiService } from '../../../core/services/user-relationship-api.service';
import { UserRelationshipStateService } from '../../../core/state/user-relationship-state.service';
import { userRelationshipStatus } from '../../../shared/constants/user-relationship-status';
import { CustomInputComponent } from '../../../shared/components/custom-input/custom-input.component';
import { CustomButtonComponent } from '../../../shared/components/custom-button/custom-button.component';
import { FriendPending } from '../../../shared/types/user';

@Component({
  selector: 'app-add-friend-sidebar',
  standalone: true,
  imports: [FormsModule, NzTabsModule, NzIconModule, NzToolTipModule, CustomInputComponent, CustomButtonComponent],
  template: `
    <div class="panel">
      <div class="header">
        <span nz-icon nzType="team"></span>
        <span style="margin-left: 8px">Friends</span>
        <nz-tabset [(nzSelectedIndex)]="tabIndex" nzSize="small" style="margin-left: 32px">
          <nz-tab nzTitle="Pending"></nz-tab>
          <nz-tab nzTitle="Add Friend"></nz-tab>
        </nz-tabset>
      </div>
      <div style="padding: 16px; color: #fff; flex: 1">
        @if (tabIndex === 1) {
          <h3>Add Friend</h3>
          <p>You can add friends with their KenVerse username</p>
          <div style="position: relative">
            <app-custom-input [(ngModel)]="addresseeName" [customStyle]="inputStyle" />
            <app-custom-button
              [buttonStyle]="{ position: 'absolute', top: '4px', right: '4px', backgroundColor: '#5865F2', color: '#fff' }"
              [disabled]="!addresseeName.trim()"
              (click)="sendRequest()"
            >
              Send Friend Request
            </app-custom-button>
          </div>
          @if (messageSubmit) { <p>{{ messageSubmit }}</p> }
        } @else {
          @if (friendPending.length === 0) {
            <p style="color: #aaa">No pending friend requests.</p>
          } @else {
            @for (friend of receivedRequests; track friend.id) {
              <div class="request-item">
                <div>
                  <strong>{{ friend.displayName }}</strong>
                  <div style="color: #aaa">{{ friend.userName }}</div>
                </div>
                <div>
                  <app-custom-button [buttonStyle]="btnStyle" (click)="accept(friend.id)"><span nz-icon nzType="check"></span></app-custom-button>
                  <app-custom-button [buttonStyle]="btnStyle" (click)="cancel(friend.id)"><span nz-icon nzType="stop"></span></app-custom-button>
                </div>
              </div>
            }
            @for (friend of sentRequests; track friend.id) {
              <div class="request-item">
                <div>
                  <strong>{{ friend.displayName }}</strong>
                  <div style="color: #aaa">{{ friend.userName }}</div>
                </div>
                <app-custom-button [buttonStyle]="btnStyle" (click)="cancel(friend.id)"><span nz-icon nzType="close"></span></app-custom-button>
              </div>
            }
          }
        }
      </div>
    </div>
  `,
  styles: [`
    .panel { background-color: rgb(48 48 49); display: flex; flex-direction: column; height: 100%; border-top-right-radius: 20px; border-bottom-right-radius: 20px; }
    .header { border-bottom: 1px solid #555; height: 59px; display: flex; align-items: center; padding-left: 16px; color: #fff; }
    .request-item { display: flex; justify-content: space-between; align-items: center; background-color: #2c2c2f; padding: 12px 16px; border-radius: 8px; margin-bottom: 12px; }
  `],
})
export class AddFriendSidebarComponent {
  @Input() friendPending: FriendPending[] = [];

  private readonly authState = inject(AuthStateService);
  private readonly api = inject(UserRelationshipApiService);
  private readonly state = inject(UserRelationshipStateService);

  tabIndex = 1;
  addresseeName = '';
  messageSubmit = '';
  inputStyle = { backgroundColor: '#212126', color: '#fff', borderColor: '#212126', paddingRight: '120px', height: '50px' };
  btnStyle = { width: '40px', height: '40px', color: '#fff', border: '1px solid #393b47', backgroundColor: '#393b47', borderRadius: '100%', marginRight: '12px' };

  get receivedRequests(): FriendPending[] {
    return this.friendPending.filter((f) => f.isSender);
  }

  get sentRequests(): FriendPending[] {
    return this.friendPending.filter((f) => !f.isSender);
  }

  async sendRequest(): Promise<void> {
    const ownerId = this.authState.user?.id;
    if (!ownerId || !this.addresseeName.trim()) return;
    try {
      const response = await this.api.addFriend({ requesterId: ownerId, addresseeName: this.addresseeName });
      if (!response.isSuccess) throw new Error(response.message);
      this.state.addFriendPending({
        id: response.data.id,
        userName: response.data.userName,
        displayName: response.data.displayName,
        avatarUrl: response.data.avatarUrl,
        isSender: false,
      });
      this.messageSubmit = `Friend request sent successfully to ${this.addresseeName}`;
    } catch (err: unknown) {
      this.messageSubmit = err instanceof Error ? err.message : 'Add friend failed';
    }
  }

  async accept(friendId: string): Promise<void> {
    const ownerId = this.authState.user?.id;
    if (!ownerId) return;
    const response = await this.api.updateUserRelationship({
      userID: ownerId,
      friendID: friendId,
      status: userRelationshipStatus.Accepted,
    });
    if (response.isSuccess) {
      this.state.removeFriendPending(friendId);
      this.state.addFriend(response.data);
    }
  }

  async cancel(friendId: string): Promise<void> {
    const ownerId = this.authState.user?.id;
    if (!ownerId) return;
    const response = await this.api.cancelFriendRequest({ userID: ownerId, friendID: friendId });
    if (response.isSuccess) this.state.removeFriendPending(friendId);
  }
}
